"""Shared state schema for the Multi-Agent Research Assistant.

All agents read from and write to this state. Fields using `Annotated[list, operator.add]`
are safe for parallel agent execution — LangGraph merges results automatically.
"""

from __future__ import annotations

import operator
from dataclasses import dataclass, field
from typing import Annotated, Any, TypedDict

from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages


# ── Reducers ─────────────────────────────────────────────────


def take_latest(left: Any, right: Any) -> Any:
    """Always take the newest value (right) over the old one (left)."""
    return right


# ── Data Models ──────────────────────────────────────────────


@dataclass
class SearchResult:
    """A single search result from Tavily."""

    url: str
    title: str
    snippet: str
    score: float = 0.0

    def to_dict(self) -> dict:
        return {"url": self.url, "title": self.title, "snippet": self.snippet, "score": self.score}

    @classmethod
    def from_dict(cls, data: dict) -> SearchResult:
        return cls(
            url=data["url"],
            title=data["title"],
            snippet=data["snippet"],
            score=data.get("score", 0.0),
        )


@dataclass
class PageContent:
    """Scraped and summarized content from a web page."""

    url: str
    title: str
    raw_content: str
    summary: str
    word_count: int = 0
    extraction_method: str = "tavily"  # "tavily" or "httpx"

    def to_dict(self) -> dict:
        return {
            "url": self.url,
            "title": self.title,
            "raw_content": self.raw_content,
            "summary": self.summary,
            "word_count": self.word_count,
            "extraction_method": self.extraction_method,
        }

    @classmethod
    def from_dict(cls, data: dict) -> PageContent:
        return cls(
            url=data["url"],
            title=data["title"],
            raw_content=data["raw_content"],
            summary=data["summary"],
            word_count=data.get("word_count", 0),
            extraction_method=data.get("extraction_method", "tavily"),
        )


@dataclass
class Finding:
    """A single research finding with source attribution."""

    claim: str
    evidence: str
    source_url: str
    confidence: float = 0.0  # 0.0 to 1.0

    def to_dict(self) -> dict:
        return {
            "claim": self.claim,
            "evidence": self.evidence,
            "source_url": self.source_url,
            "confidence": self.confidence,
        }

    @classmethod
    def from_dict(cls, data: dict) -> Finding:
        return cls(
            claim=data["claim"],
            evidence=data["evidence"],
            source_url=data["source_url"],
            confidence=data.get("confidence", 0.0),
        )


@dataclass
class AnalysisResult:
    """Structured analysis output from the Analyst agent."""

    key_findings: list[Finding] = field(default_factory=list)
    conflicts: list[str] = field(default_factory=list)
    knowledge_gaps: list[str] = field(default_factory=list)
    follow_up_queries: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "key_findings": [f.to_dict() for f in self.key_findings],
            "conflicts": self.conflicts,
            "knowledge_gaps": self.knowledge_gaps,
            "follow_up_queries": self.follow_up_queries,
        }

    @classmethod
    def from_dict(cls, data: dict) -> AnalysisResult:
        return cls(
            key_findings=[Finding.from_dict(f) for f in data.get("key_findings", [])],
            conflicts=data.get("conflicts", []),
            knowledge_gaps=data.get("knowledge_gaps", []),
            follow_up_queries=data.get("follow_up_queries", []),
        )


# ── Shared Research State ────────────────────────────────────


class ResearchState(TypedDict, total=False):
    """The shared state that all agents read from and write to.

    Fields annotated with `operator.add` support parallel writes —
    when multiple agents run simultaneously via LangGraph's Send API,
    their list outputs are concatenated instead of overwritten.
    """

    # ── Input ────────────────────────────────────────────────
    query: str  # The user's research question
    needs_clarification: Annotated[bool, take_latest]
    clarification_question: Annotated[str, take_latest]

    # ── Search phase ─────────────────────────────────────────
    search_queries: list[str]  # Sub-queries generated by the supervisor
    search_results: Annotated[list[dict], operator.add]  # Tavily search results (serialized)

    # ── Content extraction phase ─────────────────────────────
    scraped_content: Annotated[list[dict], operator.add]  # Extracted page content (serialized)

    # ── Analysis phase ───────────────────────────────────────
    analysis: dict | None  # Structured analysis (serialized AnalysisResult)
    critique: Annotated[str, take_latest]  # Evaluation from Critic agent
    limitations_log: Annotated[list[dict], operator.add]  # Critic's log of gaps

    # ── Output phase ─────────────────────────────────────────
    report: str  # Final markdown report

    # ── Conversation & control flow ──────────────────────────
    messages: Annotated[list[BaseMessage], add_messages]  # LLM conversation history
    human_feedback: str | None  # Input from HITL interrupt
    status: Annotated[str, take_latest]  # Current pipeline stage
    errors: Annotated[list[str], operator.add]  # Error log for debugging

    # ── Routing (set by supervisor, read by graph edges) ────
    next: Annotated[str, take_latest]  # Next node to route to

    # ── Metadata ─────────────────────────────────────────────
    iteration: int  # Current research iteration (for loops)
    max_iterations: int  # Maximum allowed iterations


# ── Helper to create initial state ───────────────────────────


def create_initial_state(query: str, max_iterations: int = 3) -> ResearchState:
    """Create a fresh ResearchState for a new research query."""
    return ResearchState(
        query=query,
        needs_clarification=False,
        clarification_question="",
        search_queries=[],
        search_results=[],
        scraped_content=[],
        analysis=None,
        report="",
        messages=[],
        human_feedback=None,
        status="initialized",
        errors=[],
        iteration=0,
        max_iterations=max_iterations,
        limitations_log=[],
    )
